// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://voyxcvgctqnmhajfpjej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZveXhjdmdjdHFubWhhamZwamVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1Njc4NTAsImV4cCI6MjA2ODE0Mzg1MH0.t0hDXWP-a6ARNUr4M_622tFuCib001rhLsk7GpBpdNY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});